version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    hostname: db
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod
    networks:
      - newsboard

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - newsboard

  server:
    container_name: server
    hostname: server
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/project
    env_file:
      - ./.env.prod
    command: >
      bash -c '
      python manage.py makemigrations news &&
      python manage.py migrate &&
      gunicorn newsboard.wsgi -b 0.0.0.0:8000'
    depends_on:
      - db
      - redis
    networks:
      - newsboard
  celery:
    container_name: celery
    build:
      context: ./
    command:
      celery -A newsboard worker -B
    environment:
      - REDIS_HOST=redis
    depends_on:
      - server
      - redis
    networks:
      - newsboard

networks:
  newsboard:
    driver: bridge